### ISSUE TITLE
Disable alignment

### ISSUE THREAD

**Issue by agrafix** [hasky-mode/hasky-extensions#1]
Thanks for this cool emacs mode! Would it be possible to add a configuration to disable alignment?

**Comment by mrkkrp** [comment]
Absolutely, I'll add this when I have time (most likely this weekend).

**Comment by mrkkrp** [comment]
Set `hasky-extensions-aligning` to `nil` and it should stop aligning the pragmas. Hope it helps! _(Note that it will take some time for MELPA to catch up with the change.)_

**Comment by agrafix** [comment]
Cool, thanks! :-)
